apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-staging
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: infrastructure-staging
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/overlays/staging
  prune: true
  wait: true
  timeout: 5m