apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-staging
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: infrastructure-operators
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/overlays/staging
  prune: true
  wait: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-production
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: infrastructure-operators
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/overlays/production
  prune: true
  wait: true
  timeout: 5m