apiVersion: ps.percona.com/v1alpha1
kind: PerconaServerMySQL
metadata:
  name: mysql
  namespace: staging
spec:
  secretsName: mysql-secrets

  mysql:
    clusterType: async
    image: percona/percona-server:8.0.36
    size: 1
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
    volumeSpec:
      persistentVolumeClaim:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi

  proxy:
    haproxy:
      enabled: true
      size: 1
      image: percona/haproxy:2.8.5
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi

  orchestrator:
    enabled: false

  backup:
    enabled: false