apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: percona-mysql-operator
  namespace: mysql-operator
spec:
  interval: 10m
  chart:
    spec:
      chart: ps-operator
      version: ">=1.0.0 <2.0.0"
      sourceRef:
        kind: HelmRepository
        name: percona
        namespace: mysql-operator
      interval: 1h
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    watchNamespace: ""